routing:

  admin_st_user_list:
    path: ^\/admin\/st_user\/list\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_user_list
  admin_st_user_edit:
    path: ^\/admin\/st_user\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_user_edit
  admin_st_user_create:
    path: ^\/admin\/st_user\/create\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_user_create
  admin_st_user_delete:
    path: ^\/admin\/st_user\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: sydneytoday/backend/st_user_delete

  admin_st_zhekou_list:
    path: ^\/admin\/st_zhekou\/list\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zhekou_list
  admin_st_zhekou_edit:
    path: ^\/admin\/st_zhekou\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zhekou_edit
  admin_st_zhekou_create:
    path: ^\/admin\/st_zhekou\/create\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zhekou_create
  admin_st_zhekou_delete:
    path: ^\/admin\/st_zhekou\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: sydneytoday/backend/st_zhekou_delete

  admin_st_xinping_list:
    path: ^\/admin\/st_xinping\/list\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_xinping_list
  admin_st_xinping_edit:
    path: ^\/admin\/st_xinping\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_xinping_edit
  admin_st_xinping_create:
    path: ^\/admin\/st_xinping\/create\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_xinping_create
  admin_st_xinping_delete:
    path: ^\/admin\/st_xinping\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: sydneytoday/backend/st_xinping_delete

  admin_st_zufang_list:
    path: ^\/admin\/st_zufang\/list\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zufang_list
  admin_st_zufang_edit:
    path: ^\/admin\/st_zufang\/edit\/(\d+)\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zufang_edit
  admin_st_zufang_create:
    path: ^\/admin\/st_zufang\/create\/?$
    isSecure: 1
    i18n: 1
    controller: sydneytoday/backend/st_zufang_create
  admin_st_zufang_delete:
    path: ^\/admin\/st_zufang\/delete\/(\d+)\/?$
    isSecure: 1
    i18n: 0
    controller: sydneytoday/backend/st_zufang_delete