
sitename: 
  plain: 顶贴器
  
backend_per_page: 50

tigtag:
  general_pwd: 0172122a
  general_email: findloveinsydney@gmail.com


dingtie_messages:
  - 看上去不错啊
  - 有其他联系方式吗
  - 有点小贵吧
  - 上qq吗？方便留个号码？
  - 帮顶下。。
  - 我住在Ashfield
  - 电话没打通啊，是不是关机了
  - 你好，我的qq22343433，欢迎加我联系
  - 留个电话吧
  - 无聊啊，帮你顶下
  - 现在的帖子沉得特别快
  - 还好， 不贵
  - 你在哪个区？
  - Good stuff!
  - 想看看，联系一下
  - 每天顶贴累不累
  - 你好，已私信
  - 私信已发送
  - 方便留个联络方式吗
  - 不错不错。。
  - 在哪里啊，远不远
  - 不要沉了，顶下
  - 我是雷锋，谢谢
  - 价格还可以，实惠
  - 我的名字叫红领巾
  - 留言帮顶留名百世
  - 好东东，不错
  - 看看，还想还不错啊
  - 私信好像没人看
  - 发私信比较好
  - 还是直接给我联系方式吧
  - 挺好，试试看
  - 给你顶下
  - 顶你，顶顶顶
  - 帖子沉的快啊